import Header from './components/Header'
import NavBar from './components/NavBar'
import SearchBar from './components/SearchBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Header/> 

        <NavBar/>

        <SearchBar/>

        {children}
        
      </body>
    </html>
  )
}
